/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VowelsRouteImport } from './routes/vowels'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as SyllableChartRouteImport } from './routes/syllable-chart'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PronounceRouteImport } from './routes/pronounce'
import { Route as ConsonantsRouteImport } from './routes/consonants'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'

const VowelsRoute = VowelsRouteImport.update({
  id: '/vowels',
  path: '/vowels',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllableChartRoute = SyllableChartRouteImport.update({
  id: '/syllable-chart',
  path: '/syllable-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PronounceRoute = PronounceRouteImport.update({
  id: '/pronounce',
  path: '/pronounce',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsonantsRoute = ConsonantsRouteImport.update({
  id: '/consonants',
  path: '/consonants',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/consonants': typeof ConsonantsRoute
  '/pronounce': typeof PronounceRoute
  '/quiz': typeof QuizRoute
  '/syllable-chart': typeof SyllableChartRoute
  '/vocabulary': typeof VocabularyRoute
  '/vowels': typeof VowelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/consonants': typeof ConsonantsRoute
  '/pronounce': typeof PronounceRoute
  '/quiz': typeof QuizRoute
  '/syllable-chart': typeof SyllableChartRoute
  '/vocabulary': typeof VocabularyRoute
  '/vowels': typeof VowelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/consonants': typeof ConsonantsRoute
  '/pronounce': typeof PronounceRoute
  '/quiz': typeof QuizRoute
  '/syllable-chart': typeof SyllableChartRoute
  '/vocabulary': typeof VocabularyRoute
  '/vowels': typeof VowelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/consonants'
    | '/pronounce'
    | '/quiz'
    | '/syllable-chart'
    | '/vocabulary'
    | '/vowels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/consonants'
    | '/pronounce'
    | '/quiz'
    | '/syllable-chart'
    | '/vocabulary'
    | '/vowels'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/consonants'
    | '/pronounce'
    | '/quiz'
    | '/syllable-chart'
    | '/vocabulary'
    | '/vowels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  ConsonantsRoute: typeof ConsonantsRoute
  PronounceRoute: typeof PronounceRoute
  QuizRoute: typeof QuizRoute
  SyllableChartRoute: typeof SyllableChartRoute
  VocabularyRoute: typeof VocabularyRoute
  VowelsRoute: typeof VowelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vowels': {
      id: '/vowels'
      path: '/vowels'
      fullPath: '/vowels'
      preLoaderRoute: typeof VowelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllable-chart': {
      id: '/syllable-chart'
      path: '/syllable-chart'
      fullPath: '/syllable-chart'
      preLoaderRoute: typeof SyllableChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronounce': {
      id: '/pronounce'
      path: '/pronounce'
      fullPath: '/pronounce'
      preLoaderRoute: typeof PronounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consonants': {
      id: '/consonants'
      path: '/consonants'
      fullPath: '/consonants'
      preLoaderRoute: typeof ConsonantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  ConsonantsRoute: ConsonantsRoute,
  PronounceRoute: PronounceRoute,
  QuizRoute: QuizRoute,
  SyllableChartRoute: SyllableChartRoute,
  VocabularyRoute: VocabularyRoute,
  VowelsRoute: VowelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
