/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VowelsRouteImport } from './routes/vowels'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TypingRouteImport } from './routes/typing'
import { Route as SyllableChartRouteImport } from './routes/syllable-chart'
import { Route as StrokeOrderRouteImport } from './routes/stroke-order'
import { Route as RomanizationGuideRouteImport } from './routes/romanization-guide'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PronounceRouteImport } from './routes/pronounce'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as KoreaFactsRouteImport } from './routes/korea-facts'
import { Route as IpaGuideRouteImport } from './routes/ipa-guide'
import { Route as EnglishGuideRouteImport } from './routes/english-guide'
import { Route as DutchGuideRouteImport } from './routes/dutch-guide'
import { Route as ContrastDrillsRouteImport } from './routes/contrast-drills'
import { Route as ConsonantsRouteImport } from './routes/consonants'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as BatchimRouteImport } from './routes/batchim'
import { Route as IndexRouteImport } from './routes/index'

const VowelsRoute = VowelsRouteImport.update({
  id: '/vowels',
  path: '/vowels',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TypingRoute = TypingRouteImport.update({
  id: '/typing',
  path: '/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllableChartRoute = SyllableChartRouteImport.update({
  id: '/syllable-chart',
  path: '/syllable-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeOrderRoute = StrokeOrderRouteImport.update({
  id: '/stroke-order',
  path: '/stroke-order',
  getParentRoute: () => rootRouteImport,
} as any)
const RomanizationGuideRoute = RomanizationGuideRouteImport.update({
  id: '/romanization-guide',
  path: '/romanization-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PronounceRoute = PronounceRouteImport.update({
  id: '/pronounce',
  path: '/pronounce',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const KoreaFactsRoute = KoreaFactsRouteImport.update({
  id: '/korea-facts',
  path: '/korea-facts',
  getParentRoute: () => rootRouteImport,
} as any)
const IpaGuideRoute = IpaGuideRouteImport.update({
  id: '/ipa-guide',
  path: '/ipa-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishGuideRoute = EnglishGuideRouteImport.update({
  id: '/english-guide',
  path: '/english-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DutchGuideRoute = DutchGuideRouteImport.update({
  id: '/dutch-guide',
  path: '/dutch-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrastDrillsRoute = ContrastDrillsRouteImport.update({
  id: '/contrast-drills',
  path: '/contrast-drills',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsonantsRoute = ConsonantsRouteImport.update({
  id: '/consonants',
  path: '/consonants',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchimRoute = BatchimRouteImport.update({
  id: '/batchim',
  path: '/batchim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batchim': typeof BatchimRoute
  '/blocks': typeof BlocksRoute
  '/builder': typeof BuilderRoute
  '/consonants': typeof ConsonantsRoute
  '/contrast-drills': typeof ContrastDrillsRoute
  '/dutch-guide': typeof DutchGuideRoute
  '/english-guide': typeof EnglishGuideRoute
  '/ipa-guide': typeof IpaGuideRoute
  '/korea-facts': typeof KoreaFactsRoute
  '/learn': typeof LearnRoute
  '/progress': typeof ProgressRoute
  '/pronounce': typeof PronounceRoute
  '/quiz': typeof QuizRoute
  '/romanization-guide': typeof RomanizationGuideRoute
  '/stroke-order': typeof StrokeOrderRoute
  '/syllable-chart': typeof SyllableChartRoute
  '/typing': typeof TypingRoute
  '/vocabulary': typeof VocabularyRoute
  '/vowels': typeof VowelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batchim': typeof BatchimRoute
  '/blocks': typeof BlocksRoute
  '/builder': typeof BuilderRoute
  '/consonants': typeof ConsonantsRoute
  '/contrast-drills': typeof ContrastDrillsRoute
  '/dutch-guide': typeof DutchGuideRoute
  '/english-guide': typeof EnglishGuideRoute
  '/ipa-guide': typeof IpaGuideRoute
  '/korea-facts': typeof KoreaFactsRoute
  '/learn': typeof LearnRoute
  '/progress': typeof ProgressRoute
  '/pronounce': typeof PronounceRoute
  '/quiz': typeof QuizRoute
  '/romanization-guide': typeof RomanizationGuideRoute
  '/stroke-order': typeof StrokeOrderRoute
  '/syllable-chart': typeof SyllableChartRoute
  '/typing': typeof TypingRoute
  '/vocabulary': typeof VocabularyRoute
  '/vowels': typeof VowelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batchim': typeof BatchimRoute
  '/blocks': typeof BlocksRoute
  '/builder': typeof BuilderRoute
  '/consonants': typeof ConsonantsRoute
  '/contrast-drills': typeof ContrastDrillsRoute
  '/dutch-guide': typeof DutchGuideRoute
  '/english-guide': typeof EnglishGuideRoute
  '/ipa-guide': typeof IpaGuideRoute
  '/korea-facts': typeof KoreaFactsRoute
  '/learn': typeof LearnRoute
  '/progress': typeof ProgressRoute
  '/pronounce': typeof PronounceRoute
  '/quiz': typeof QuizRoute
  '/romanization-guide': typeof RomanizationGuideRoute
  '/stroke-order': typeof StrokeOrderRoute
  '/syllable-chart': typeof SyllableChartRoute
  '/typing': typeof TypingRoute
  '/vocabulary': typeof VocabularyRoute
  '/vowels': typeof VowelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batchim'
    | '/blocks'
    | '/builder'
    | '/consonants'
    | '/contrast-drills'
    | '/dutch-guide'
    | '/english-guide'
    | '/ipa-guide'
    | '/korea-facts'
    | '/learn'
    | '/progress'
    | '/pronounce'
    | '/quiz'
    | '/romanization-guide'
    | '/stroke-order'
    | '/syllable-chart'
    | '/typing'
    | '/vocabulary'
    | '/vowels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batchim'
    | '/blocks'
    | '/builder'
    | '/consonants'
    | '/contrast-drills'
    | '/dutch-guide'
    | '/english-guide'
    | '/ipa-guide'
    | '/korea-facts'
    | '/learn'
    | '/progress'
    | '/pronounce'
    | '/quiz'
    | '/romanization-guide'
    | '/stroke-order'
    | '/syllable-chart'
    | '/typing'
    | '/vocabulary'
    | '/vowels'
  id:
    | '__root__'
    | '/'
    | '/batchim'
    | '/blocks'
    | '/builder'
    | '/consonants'
    | '/contrast-drills'
    | '/dutch-guide'
    | '/english-guide'
    | '/ipa-guide'
    | '/korea-facts'
    | '/learn'
    | '/progress'
    | '/pronounce'
    | '/quiz'
    | '/romanization-guide'
    | '/stroke-order'
    | '/syllable-chart'
    | '/typing'
    | '/vocabulary'
    | '/vowels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchimRoute: typeof BatchimRoute
  BlocksRoute: typeof BlocksRoute
  BuilderRoute: typeof BuilderRoute
  ConsonantsRoute: typeof ConsonantsRoute
  ContrastDrillsRoute: typeof ContrastDrillsRoute
  DutchGuideRoute: typeof DutchGuideRoute
  EnglishGuideRoute: typeof EnglishGuideRoute
  IpaGuideRoute: typeof IpaGuideRoute
  KoreaFactsRoute: typeof KoreaFactsRoute
  LearnRoute: typeof LearnRoute
  ProgressRoute: typeof ProgressRoute
  PronounceRoute: typeof PronounceRoute
  QuizRoute: typeof QuizRoute
  RomanizationGuideRoute: typeof RomanizationGuideRoute
  StrokeOrderRoute: typeof StrokeOrderRoute
  SyllableChartRoute: typeof SyllableChartRoute
  TypingRoute: typeof TypingRoute
  VocabularyRoute: typeof VocabularyRoute
  VowelsRoute: typeof VowelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vowels': {
      id: '/vowels'
      path: '/vowels'
      fullPath: '/vowels'
      preLoaderRoute: typeof VowelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typing': {
      id: '/typing'
      path: '/typing'
      fullPath: '/typing'
      preLoaderRoute: typeof TypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllable-chart': {
      id: '/syllable-chart'
      path: '/syllable-chart'
      fullPath: '/syllable-chart'
      preLoaderRoute: typeof SyllableChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke-order': {
      id: '/stroke-order'
      path: '/stroke-order'
      fullPath: '/stroke-order'
      preLoaderRoute: typeof StrokeOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romanization-guide': {
      id: '/romanization-guide'
      path: '/romanization-guide'
      fullPath: '/romanization-guide'
      preLoaderRoute: typeof RomanizationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronounce': {
      id: '/pronounce'
      path: '/pronounce'
      fullPath: '/pronounce'
      preLoaderRoute: typeof PronounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korea-facts': {
      id: '/korea-facts'
      path: '/korea-facts'
      fullPath: '/korea-facts'
      preLoaderRoute: typeof KoreaFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipa-guide': {
      id: '/ipa-guide'
      path: '/ipa-guide'
      fullPath: '/ipa-guide'
      preLoaderRoute: typeof IpaGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-guide': {
      id: '/english-guide'
      path: '/english-guide'
      fullPath: '/english-guide'
      preLoaderRoute: typeof EnglishGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dutch-guide': {
      id: '/dutch-guide'
      path: '/dutch-guide'
      fullPath: '/dutch-guide'
      preLoaderRoute: typeof DutchGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrast-drills': {
      id: '/contrast-drills'
      path: '/contrast-drills'
      fullPath: '/contrast-drills'
      preLoaderRoute: typeof ContrastDrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consonants': {
      id: '/consonants'
      path: '/consonants'
      fullPath: '/consonants'
      preLoaderRoute: typeof ConsonantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batchim': {
      id: '/batchim'
      path: '/batchim'
      fullPath: '/batchim'
      preLoaderRoute: typeof BatchimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchimRoute: BatchimRoute,
  BlocksRoute: BlocksRoute,
  BuilderRoute: BuilderRoute,
  ConsonantsRoute: ConsonantsRoute,
  ContrastDrillsRoute: ContrastDrillsRoute,
  DutchGuideRoute: DutchGuideRoute,
  EnglishGuideRoute: EnglishGuideRoute,
  IpaGuideRoute: IpaGuideRoute,
  KoreaFactsRoute: KoreaFactsRoute,
  LearnRoute: LearnRoute,
  ProgressRoute: ProgressRoute,
  PronounceRoute: PronounceRoute,
  QuizRoute: QuizRoute,
  RomanizationGuideRoute: RomanizationGuideRoute,
  StrokeOrderRoute: StrokeOrderRoute,
  SyllableChartRoute: SyllableChartRoute,
  TypingRoute: TypingRoute,
  VocabularyRoute: VocabularyRoute,
  VowelsRoute: VowelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
